[package]
name = "grafx"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30.0"
env_logger = "0.11.3"
wgpu = "0.20.0"
pollster = "0.3.0"
glam = "0.27.0"
bytemuck = { version = "1.16.0", features = ["derive"] }
image = "0.25.1"
log = "0.4.21"

[profile.dev.package."*"]
opt-level = 2
